CREATE TABLE IF NOT EXISTS PRESENTE (
      ID_PRESENTE INT(11) PRIMARY KEY,
      NOME VARCHAR(255),
      DESCRICAO_PRESENTE TEXT,
      ID_USUARIO INT(11),
      FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
    );

CREATE TABLE IF NOT EXISTS USUARIO {
        ID_USUARIO INT(11) PRIMARY KEY,
        NOME VARCHAR(255),
        SENHA_ALTERNATIVA VARCHAR(20),
    }
