CREATE TABLE IF NOT EXISTS PRESENTE (
    ID_PRESENTE INT PRIMARY KEY,
    NOME VARCHAR(255),
    DESCRICAO_PRESENTE TEXT,
    ID_USUARIO INT,
    COMPRADO BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
    );
